version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: deskplus-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deskplus
    ports:
      - '3306:3306'
    volumes:
      - deskplus_mysql_data:/var/lib/mysql

volumes:
  deskplus_mysql_data:
