<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('reference', 20)->unique(); // DSK-00001 — generated by observer
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); // null = guest
            $table->string('status', 20)->default('pending'); // pending|preparing|shipping|delivered|cancelled
            $table->decimal('subtotal', 10, 2);
            $table->unsignedBigInteger('discount_id')->nullable();
            $table->foreign('discount_id')->references('id')->on('discounts')->nullOnDelete();
            $table->decimal('discount_amount', 10, 2)->default(0.00);
            $table->decimal('shipping_cost', 10, 2)->default(0.00);
            $table->decimal('tax', 10, 2)->default(0.00);
            $table->decimal('total', 10, 2);
            $table->string('payment_method', 50)->nullable(); // card | cash | bank_transfer
            $table->string('payment_status', 20)->default('pending'); // pending|paid|failed|refunded
            $table->text('notes')->nullable();
            $table->timestamps();

            $table->index('reference');
            $table->index('user_id');
            $table->index('status');
            $table->index('payment_status');
            $table->index('created_at');
            $table->index('discount_id');
        });

        Schema::create('order_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->constrained()->cascadeOnDelete();
            $table->foreignId('product_id')->constrained()->restrictOnDelete();
            $table->foreignId('variant_id')->nullable()->constrained('product_variants')->nullOnDelete();
            $table->string('product_name', 200);  // SNAPSHOT — never changes even if product renamed
            $table->string('variant_info', 100)->nullable(); // SNAPSHOT e.g. "Black / Oak"
            $table->integer('quantity');
            $table->decimal('unit_price', 10, 2); // SNAPSHOT — price at time of order
            $table->decimal('total', 10, 2);       // quantity × unit_price

            $table->index('order_id');
            $table->index('product_id');
        });

        Schema::create('shipping_addresses', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->unique()->constrained()->cascadeOnDelete();
            $table->string('first_name', 80);
            $table->string('last_name', 80);
            $table->string('email', 150);
            $table->string('phone', 20);
            $table->string('address_line1');
            $table->string('address_line2')->nullable();
            $table->string('city', 100);
            $table->string('state', 100)->nullable();
            $table->string('country', 100)->default('Morocco');
            $table->string('postal_code', 20)->nullable();
            $table->timestamp('created_at')->useCurrent();
        });

        Schema::create('order_status_history', function (Blueprint $table) {
            $table->id();
            $table->foreignId('order_id')->constrained()->cascadeOnDelete();
            $table->string('status', 20);
            $table->text('note')->nullable();
            $table->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('created_at')->useCurrent();

            $table->index('order_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('order_status_history');
        Schema::dropIfExists('shipping_addresses');
        Schema::dropIfExists('order_items');
        Schema::dropIfExists('orders');
    }
};
